### PR TITLE
Some enhancements

### PR DESCRIPTION
**Pull request by MZade**
Hi, 

I've implemented two enhancements on the RIS. Would be great if we may include these in the master branch. Thanks!

See the details here bellow:

**ImportFromPackage relative path by configuration**
This change will use the configuration from the RecurringIntegrationsScheduler.Common.dll.config to get the ImportFromPackage relative path from the configuration file, if defined. If the value is not defined in the dll configuration file, it will use the original value.
This feature helps you implementing a custom version of ImportFromPackage.

**Use original file name to upload**
To increase the traceability of the files getting uploaded to D365FO, the Manifest.xml file is getting updated with the original file name before uploading the data package. Offcourse this change is also using the original file name in the data package for the data file itself. This happens right before the upload of the data package which is getting prepared based onthe template file name.

Kind regards,
Mehrdad

### CODE REVIEW

**Comment by TomekMelissa** [comment]
Hi Mehrdad,
Could you please remove the part with custom relative path? The part about keeping original file name looks good and I would like to include it in RIS.
I think that if we need custom path for odata actions then it should be part of job configuration. In your solution it changes it for all import jobs. Another thing is that if we want to introduce such concept then i think we need parameters for all actions.
Also i do not think we need change in Scheduler/Forms/ImportJob.resx

**Comment by MZade** [comment]
Hi @TomekMelissa, I have removed the modifications related to "ImportFromPackage relative path by configuration".
Could you please have a look now..Thanks!

**Comment by TomekMelissa** [comment]
I am sorry I missed your last comment. Could you please show me the screenshot of the problem?

**Comment by MZade** [comment]
Hi @TomekMelissa, Here is a screenshot from the issue situation whule my changes are undone.

image

**Comment by TomekMelissa** [comment]
@MehrdadMzfr All other forms look good?

**Comment by MZade** [comment]
@TomekMelissa  I think so. Here some samples of good looking forms:

image

image

image

image

**Pull request merged**
